server_name: log-demo-server
org_name: glory
log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

provider:
  "httpDemo":
    protocol: http
    service_id: glory-http-demo
    port: 8079