org_name: glory
server_name: metrics-demo-client
log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

registry:
  "registryKey":
    config_source: file
    address: localhost:6379
    service: redis

metrics:
  - client_port: 8082 # pull mod prometheus
    metrics_type: prometheus_client
    client_path: /prometheus
    action_type: pull
  - gateway_host: localhost # push gateway
    gateway_port: 9091
    action_type: push
    metrics_type: prometheus_client

provider:
  "gloryGrpcService":
    protocol: grpc
#    registry_key: registryKey
    service_id: GoOnline-IDE-gloryService
    port: 8080