org_name: ide
server_name: grpc-demo
log :
  "console-log":
    log_type: console
    level: debug

registry:
  "registryKey":
    service: k8s


consumer:
  "grpc-helloworld-demo":
    registry_key: registryKey
    config_source: file
    service_id: GoOnline-IDE-gloryService
    protocol: grpc