org_name: ide
server_name: grpc-demo

log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

registry:
  "registryKey":
    service: k8s

#metrics:
#  - client_port: 8082
#    metrics_type: prometheus_client
#    client_path: /prometheus
#    action_type: pull
#  - gateway_host: localhost
#    gateway_port: 9091
#    action_type: push
#    metrics_type: prometheus_client

provider:
  "gloryGrpcService":
    protocol: grpc
    registry_key: registryKey
    service_id: GoOnline-IDE-gloryService
    port: 8079