org_name: ide
server_name: k8s_client_demo
log :
#  "local-file-log":
#    log_type: file
#    file_path: ./log/glory_log # 自动生成路径
#    level: info
  "console-log":
    log_type: console
    level: info

registry:
  "registryKey":
    service: k8s


consumer :
  "gloryClient":
    registry_key: registryKey
    config_source: file
    service_id: GoOnline-IDE-gloryService
    protocol: glory