org_name: glory
server_name: nacos-registry-demo-server

log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

registry:
  "registryKey":
    address: localhost:8848
    service: nacos


provider:
  "gloryGrpcService":
    protocol: grpc
    registry_key: registryKey
    service_id: nacosDemoServer
    port: 8086