org_name: glory
server_name: grpc-demo-client
log :
  "console-log":
    log_type: console
    level: debug

consumer:
  "grpc-helloworld-demo":
    registry_key: registryKey
    server_address: localhost:8081
    protocol: grpc