server_name: log-demo-server
org_name: glory

log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

mq:
  "testmq":
    host: localhost
    port: 5672
    username: admin
    password: admin
    channels:
      "testqueue":
        exchange: "demo_echange"
        type: pub_sub