org_name: ide
server_name: grpc-demo

log : # 日志配置
  "console-log":
    log_type: console # 命令行输出日志
    level: debug # 日志等级

mysql:
  "dev-mysql":
    config_source: file
    host: localhost
    port: 3306
    username: root
    password: 123456
    dbname: mydb

provider:
  "gloryGrpcService":
    protocol: grpc
    service_id: GoOnline-IDE-gloryService
    port: 8079